
noSections = 9

noGroupsPerSection = 5

faculties = {
    "Mathematics and Informatics": {
        "Informatica": [
            ("Algebra", 1, 1),
            ("Fundamentele programarii", 1, 1),
            ("Arhitectura sistemelor de calcul", 1, 1),
            ("Programare in c", 3, 1),
            ("Structuri de date si algoritmi", 1, 2),
            ("Geometrie", 1, 2),
            ("Sisteme dinamice", 1, 2),
            ("Metode avansate de rezolvare a problemelor de matematica şi informatica", 3, 2),
            ("Metode avansate de programare", 1, 3),
            ("Retele de calculatoare", 1, 3),
            ("Baze de date", 1, 3),
            ("Programare functionala si logica", 1, 3),
            ("Inteligenta artificiala", 1, 4),
            ("Ingineria sistemelor soft", 1, 4),
            ("Medii de proiectare si programare", 1, 4),
            ("Programare web", 1, 4),
            ("Programare paralela si distribuita", 1, 5),
            ("Programare pentru dispozitive mobile", 1, 5),
            ("Criptografie cu cheie publica", 2, 5),
            ("Protocoale specializate in retele de calculatoare", 2, 5),
            ("Proiect de cercetare", 2, 5),
            ("Automatizarea proceselor de business", 2, 5),
            ("Calcul numeric", 1, 6),
            ("Verificarea si validarea sistemelor soft", 1, 6),
            ("Programarea orientata pe aspecte", 2, 6),
            ("Sabloane de proiectare", 2, 6),
            ("Istoria informaticii", 2, 6),
            ("Invatare interactiva", 2, 6)
        ],
        "Matematica": [
            ("Algebra 1", 1, 1),
            ("Algoritmi si programare", 1, 1),
            ("Analiza 1", 1, 1),
            ("Matematica de baza", 3, 1),
            ("Algebra 2", 1, 2),
            ("Analiza 2", 1, 2),
            ("OOP", 1, 2),
            ("Metode avansate de rezolvare a problemelor de matematica şi informatica", 3, 2),
            ("Topologie", 1, 3),
            ("Geometrie 3", 1, 3),
            ("Ecuatii diferentiale", 1, 3),
            ("Analiza convexa", 2, 3),
            ("Teoria probabilitatilor", 1, 4),
            ("Analiza numerica", 1, 4),
            ("Modelare matematica", 2, 4),
            ("Capitole speciale de ecuatii diferentiale", 2, 4),
            ("Astronomie", 1, 5),
            ("Analiza functionala", 1, 5),
            ("Matematica operatiunilor financiare", 2, 5),
            ("Metode numerice cu aplicatii", 2, 5),
            ("Metode numerice in mecanica", 2, 5),
            ("Complemente de algebra", 2, 5),
            ("Teoria numerelor", 1, 6),
            ("Complemente de mecanica si astronomie", 2, 6),
            ("Complemente de geometrie", 2, 6)
        ],
        "Matematica Informatica": [
            ("Algebra 1", 1, 1),
            ("Algoritmi si programare", 1, 1),
            ("Fundamentele programarii", 1, 1),
            ("Matematica de baza", 3, 1),
            ("Algebra 2", 1, 2),
            ("Structuri de date si algoritmi", 1, 2),
            ("OOP", 1, 2),
            ("Metode avansate de rezolvare a problemelor de matematica şi informatica", 3, 2),
            ("Topologie", 1, 3),
            ("Baze de date", 1, 3),
            ("Ecuatii diferentiale", 1, 3),
            ("Medii de proiectare si programare", 1, 4),
            ("Analiza numerica", 1, 4),
            ("Modelare matematica", 2, 4),
            ("Programare paralela si distribuita", 1, 5),
            ("Analiza functionala", 1, 5),
            ("Matematica operatiunilor financiare", 2, 5),
            ("Protocoale specializate in retele de calculatoare", 2, 5),
            ("Metode numerice in mecanica", 2, 5),
            ("Complemente de algebra", 2, 5),
            ("Verificarea si validarea sistemelor soft", 1, 6),
            ("Complemente de mecanica si astronomie", 2, 6),
            ("Invatare interactiva", 2, 6)
        ]
    },
    "Physics": {
        "Fizica": [
            ("Algebra", 1, 1),
            ("Analiza", 1, 1),
            ("Chimie generala", 3, 1),
            ("Termodinamica", 1, 2),
            ("Ecuatii diferentiale", 1, 2),
            ("Informatica aplicaa in fizica", 3, 2),
            ("Optica", 1, 3),
            ("Electronica", 1, 3),
            ("Mecanica cuantica", 3, 3),
            ("Fizica nucleara", 1, 4),
            ("Fizica atomului", 1, 4),
            ("Optia 2", 3, 4),
            ("Fizica moleculei", 1, 5),
            ("Fizica solidului", 1, 5),
            ("Spectroscopie si laseri", 2, 5),
            ("Fizica semiconductorului", 1, 6),
            ("Curs optional 1", 2, 6),
            ("Curs optional 2", 2, 6)
        ],
        "Fizica Informatica": [
            ("Algebra", 1, 1),
            ("Analiza", 1, 1),
            ("Fundamentele Programarii", 3, 1),
            ("Termodinamica", 1, 2),
            ("Ecuatii diferentiale", 1, 2),
            ("OOP", 3, 2),
            ("Optica", 1, 3),
            ("Electronica", 1, 3),
            ("Mecanica cuantica", 3, 3),
            ("Fizica nucleara", 1, 4),
            ("Metode avansate de programare", 1, 4),
            ("Optia 2", 3, 4),
            ("Fizica moleculei", 1, 5),
            ("Sisteme de operare", 1, 5),
            ("Spectroscopie si laseri", 2, 5),
            ("Fizica semiconductorului", 1, 6),
            ("Curs optional 1", 2, 6),
            ("Curs optional 2", 2, 6)
        ],
        "Fizica medicala": [
            ("Algebra", 1, 1),
            ("Analiza", 1, 1),
            ("Chimie generala", 1, 1),
            ("Termodinamica", 1, 2),
            ("Ecuatii diferentiale", 1, 2),
            ("Informatica aplicaa in fizica", 3, 2),
            ("Biofizica", 1, 3),
            ("Biochimie", 1, 3),
            ("Optica", 3, 3),
            ("Fizica nucleara", 1, 4),
            ("Fizica atomului", 1, 4),
            ("Optia 2", 3, 4),
            ("Fizica moleculei", 1, 5),
            ("Fizica solidului", 1, 5),
            ("Medicina nucleara", 2, 5),
            ("Radiologie", 1, 6),
            ("Curs optional 1", 2, 6),
            ("Curs optional 2", 2, 6)
        ]
    },
    "History and Philosophy": {
        "Istorie": [
            ("Introducere in istoria veche universala", 1, 1),
            ("Introducere in istoria veche a României", 1, 1),
            ("stiintele auxiliare ale istoriei", 3, 1),
            ("Introducere in istoria medie universala", 1, 2),
            ("Istoria Bizantului", 1, 2),
            ("Introducere in metodologia cercetarii stiintifice", 3, 2),
            ("Introducere in istoria moderna universala", 1, 3),
            ("Relaţii internaţionale in secolele XVIII-XIX", 1, 3),
            ("Istoria mentalitaţilor colective", 3, 3),
            ("Introducere in istoria contemporana universala", 1, 4),
            ("Introducere in istoria contemporana a României", 1, 4),
            ("Istoria integrarii europene", 3, 4),
            ("Istoria si teoria artei", 1, 5),
            ("Paleografii 1", 1, 5),
            ("Curs special 1", 2, 5),
            ("Introducere in teoria istoriei", 1, 6),
            ("Paleografii 2", 1, 6),
            ("Curs optional 2: Limba izvoarelor II - latina", 2, 6)
        ]
    },
    "Geography": {
        "Geografie": [
            ("Geografie generala", 1, 1),
            ("Geologie generala", 1, 1),
            ("Fundamente de antreprenoriat", 1, 1),
            ("Geomorfologie", 1, 2),
            ("Geografie regionala", 1, 2),
            ("Fundamente de antreprenoriat 2", 3, 2),
            ("Geografia asezarilor", 1, 3),
            ("Geografia fizica a romaniei", 1, 3),
            ("Toponomie geografica", 2, 3),
            ("Geografia umana a romaniei", 1, 4),
            ("Pedogeografie", 1, 4),
            ("Geografia uniunii europene", 2, 4),
            ("Geografia peisajului", 1, 5),
            ("Organizarea spatiului geografic", 1, 5),
            ("Geografie sociala", 2, 5),
            ("Geografia turismului", 1, 6),
            ("Planificare teritoriala", 2, 6),
            ("Oceanografie", 2, 6)
        ],
        "Geografia Turismului": [
            ("Geografie generala", 1, 1),
            ("Geografie generala a turismului", 1, 1),
            ("Fundamente de antreprenoriat", 1, 1),
            ("Geografia regionala a romaniei", 1, 2),
            ("Arhitectura in turism", 1, 2),
            ("Fundamente de antreprenoriat 2", 3, 2),
            ("Geografia turismului in Romania", 1, 3),
            ("Organizarea intreprinderilor si serviciilor in turism", 1, 3),
            ("Cultura si civilizatie britanica", 3, 3),
            ("Management turistic", 1, 4),
            ("Comunicare si imagine in turism", 1, 4),
            ("Istoria turismului", 2, 4),
            ("Prospectare si strategii de dezvoltare turistica", 1, 5),
            ("Ecoturism şi dezvoltare durabila", 1, 5),
            ("Turism rural", 2, 5),
            ("Geografie economica", 1, 6),
            ("Economia turismului şi intreprinderii de turism", 2, 6),
            ("Geografie sociala", 2, 6)
        ]
    }
}
